# Generated by Django 5.2.3 on 2025-07-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0006_subscription"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс, за который произведена оплата",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="educations.course",
                verbose_name="Оплаченный курс",
            ),
        ),
    ]
