# Generated by Django 5.2.3 on 2025-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью курса",
                null=True,
                upload_to="educations/previews/",
                verbose_name="Превью курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью урока",
                null=True,
                upload_to="educations/previews/",
                verbose_name="Превью урока",
            ),
        ),
    ]
