# Generated by Django 5.2.3 on 2025-06-28 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(verbose_name="Количество уроков"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="educations.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Количество уроков",
                "verbose_name_plural": "Количество уроков",
            },
        ),
    ]
