# Generated by Django 5.2.3 on 2025-06-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0002_count"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Count",
        ),
    ]
