# Generated by Django 5.2.3 on 2025-06-28 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0003_delete_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата оплаты курса или урока",
                        verbose_name="Дата платежа",
                    ),
                ),
                (
                    "payment_sum",
                    models.PositiveIntegerField(
                        help_text="Введите сумму оплаты", verbose_name="Сумма оплаты"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "наличные"), ("transfer", "перевод на счет")],
                        help_text="Выберите способ оплаты",
                        max_length=20,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Курс, за который произведена оплата",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_for_course",
                        to="educations.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Урок, за который произведена оплата",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_for_lesson",
                        to="educations.lesson",
                        verbose_name="Оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, купивший курс или урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
