# Generated by Django 5.2.3 on 2025-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0006_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notified",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
